### ISSUE TITLE
location messages crash the echo demo

### ISSUE THREAD

**Issue by renemendoza** [AragurDEV/yowsup#14]
location messages make the Echo demo crash. regular text message work fine

``` bash

(AragurDev-yowsup) ➜  AragurDEV-yowsup git:(master) ✗ python yowsup-cli demos -e -lXXX:XXXX -E s40
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


ERROR:yowsup.layers.axolotl.layer_receive:AttributeError: 'bytes' object has no attribute 'encode'. Skipping 'encode()'
Echoing Hola to 521XXXXXXXXX

ERROR:yowsup.layers.axolotl.layer_receive:AttributeError: 'bytes' object has no attribute 'encode'. Skipping 'encode()'
Echoing location (21.1686663, -86.8198473) to 521XXXXXXXXX
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 270, in process
    self.startEcho()
  File "yowsup-cli", line 308, in startEcho
    stack.start()
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/Users/rene/.pyenv/versions/3.5.0/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/Users/rene/.pyenv/versions/3.5.0/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/Users/rene/.pyenv/versions/3.5.0/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/Users/rene/.pyenv/versions/3.5.0/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/Users/rene/.pyenv/versions/3.5.0/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_receive.py", line 42, in receive
    self.onMessage(protocolTreeNode)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_receive.py", line 75, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_receive.py", line 89, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_receive.py", line 145, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_receive.py", line 204, in parseAndHandleMessageProto
    self.handleLocationMessage(node, m.location_message)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_receive.py", line 269, in handleLocationMessage
    self.toUpper(messageNode)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/protocol_media/layer.py", line 51, in recvMessageStanza
    self.toUpper(entity)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/demos/echoclient/layer.py", line 13, in onMessage
    self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/protocol_media/layer.py", line 35, in sendMessageEntity
    self.entityToLower(entity)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_send.py", line 114, in send
    self.handleEncNode(node)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_send.py", line 68, in handleEncNode
    messageData = self.serializeToProtobuf(node)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_send.py", line 286, in serializeToProtobuf
    return self.serializeMediaToProtobuf(node.getChild("enc"), message)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_send.py", line 299, in serializeMediaToProtobuf
    return self.serializeLocationToProtobuf(mediaNode, message)
  File "/Users/rene/code/whatsapp/AragurDEV-yowsup/yowsup/layers/axolotl/layer_send.py", line 314, in serializeLocationToProtobuf
    location_message.url = mediaNode["url"]
  File "/Users/rene/.pyenv/versions/AragurDev-yowsup/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/rene/.pyenv/versions/AragurDev-yowsup/lib/python3.5/site-packages/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
    raise TypeError(message)
TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)

```

**Comment by AragurDEV** [comment]
We have to look into that.
Thanks for your report

**Comment by schoerg** [comment]
https://github.com/tgalal/yowsup/pull/1721/files

**Comment by AragurDEV** [comment]
@schoerg 
It was already fixed... https://github.com/AragurDEV/yowsup/blob/master/yowsup/layers/axolotl/layer_receive.py
