### ISSUE TITLE
Connection reset by peer when sending Media

### ISSUE THREAD

**Issue by xwanyiri** [AragurDEV/yowsup#19]
The previous fix to send Videos was working until recently. Now when i try to send either a Video or photo i either get this error
 `Error occured at transfer [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 169, in run
    ssl_sock.write(stream[:buf])
  File "/usr/lib/python3.5/ssl.py", line 808, in write
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
`
or this, especially for images

`Error occured at transfer json data not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 204, in run
    raise Exception("json data not found")
Exception: json data not found
`
Does anyone know how to resolve this?

**Comment by galaxyitcenter** [comment]
https://github.com/AragurDEV/yowsup/issues/16

**Comment by galaxyitcenter** [comment]
Fixed it.
https://github.com/AragurDEV/yowsup/pull/20
