### ISSUE TITLE
python3 setup.py install 

### ISSUE THREAD

**Issue by qvs5010** [AragurDEV/yowsup#48]
Hi 

When I run the python3 setup.py install I get the following error. 

Must I add a module to python?

 ```
File "/tmp/easy_install-7y28f4ro/preview_generator-0.2.2/setup.py", line 25, in <module>
    license='GPL-3+',
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1357: ordinal not in range(128)
```

**Comment by AragurDEV** [comment]
Did you check the dependencies?

**Comment by qvs5010** [comment]
Hi Dev

Yes

I got all the following dependancies.


Requires python3.0 + (python2.6 + no longer support)
Required python packages: python-dateutil, libmagickwand-dev
Required python packages for end-to-end encryption: protobuf, pycrypto, python-axolotl-curve25519
Required python packages for yowsup-cli: argparse, readline (or pyreadline for windows), pillow (for sending images)
Install using setup.py to pull all python dependencies


```
[root@panel wdownloads]# pip install python-dateutil
Requirement already satisfied: python-dateutil in /usr/lib/python3.4/site-packages/python_dateutil-2.6.1-py3.4.egg
Requirement already satisfied: six>=1.5 in /usr/lib/python3.4/site-packages/six-1.10.0-py3.4.egg (from python-dateutil)
[root@panel wdownloads]# pip3 install python-dateutil
Requirement already satisfied: python-dateutil in /usr/lib/python3.4/site-packages/python_dateutil-2.6.1-py3.4.egg
Requirement already satisfied: six>=1.5 in /usr/lib/python3.4/site-packages/six-1.10.0-py3.4.egg (from python-dateutil)
[root@panel wdownloads]# pip3 install pycrypto
Requirement already satisfied: pycrypto in /usr/lib/python3.4/site-packages/pycrypto-2.6.1-py3.4-linux-x86_64.egg
[root@panel wdownloads]# pip3 install python-axolotl-curve25519
Requirement already satisfied: python-axolotl-curve25519 in /usr/lib/python3.4/site-packages/python_axolotl_curve25519-0.1-py3.4-linux-x86_64.egg
[root@panel wdownloads]# pip3 install argparse
Requirement already satisfied: argparse in /usr/lib/python3.4/site-packages/argparse-1.1-py3.4.egg
[root@panel wdownloads]# pip3 install readline
Requirement already satisfied: readline in /usr/lib64/python3.4/site-packages
[root@panel wdownloads]# pip3 install pillow
Requirement already satisfied: pillow in /usr/lib64/python3.4/site-packages

```

is there one I miss?

**Comment by qvs5010** [comment]
```
Best match: preview-generator 0.2.2
Downloading https://pypi.python.org/packages/2b/e1/007d665684274d48f2901211cf5b5b5b1747490fbc45a29f5089ad9d9c9e/preview_generator-0.2.2.tar.gz#md5=6731436e30359dc30dbcd30d9d38797f
Processing preview_generator-0.2.2.tar.gz
Writing /tmp/easy_install-x1hghgk2/preview_generator-0.2.2/setup.cfg
Running preview_generator-0.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x1hghgk2/preview_generator-0.2.2/egg-dist-tmp-gin1zwu1
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-x1hghgk2/preview_generator-0.2.2/setup.py", line 25, in <module>
    license='GPL-3+',
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1357: ordinal not in range(128)

During handling of the above exception, another exception occurred:

```

**Comment by qvs5010** [comment]
was missing pip3 install preview-generator that fixed it, thanks for all the help!!!!
