### ISSUE TITLE
Error: TypeError: 'Hola' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)

### ISSUE THREAD

**Issue by viktordart** [AragurDEV/yowsup#61]
Hi!
I'm use the command : python3 yowsup-cli demos -c config --send 34999999999 "Hola" and i recived the next error:

Traceback (most recent call last):
  File "yowsup-cli", line 384, in <module>
    if not parser.process():
  File "yowsup-cli", line 288, in process
    self.startSendClient()
  File "yowsup-cli", line 340, in startSendClient
    stack.start()
  File "/home/victor/Descargas/yowsup-master/yowsup/demos/sendclient/stack.py", line 32, in start
    self.stack.loop()
  File "/home/victor/Descargas/yowsup-master/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 55, in receive
    self.toUpper(protocolTreeNode)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 75, in handleSuccess
    self.toUpper(nodeEntity)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/victor/Descargas/yowsup-master/yowsup/demos/sendclient/layer.py", line 31, in onSuccess
    self.toLower(messageEntity)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 107, in send
    self.processPlaintextNodeAndSend(node)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 155, in processPlaintextNodeAndSend
    self.sendToContact(node)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 213, in sendToContact
    messageData = self.serializeToProtobuf(node).SerializeToString() + self.getPadding()
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 291, in serializeToProtobuf
    return self.serializeTextToProtobuf(node, message)
  File "/home/victor/Descargas/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 299, in serializeTextToProtobuf
    m.conversation = node.getChild("body").getData()
  File "/usr/local/lib/python3.6/dist-packages/protobuf-3.5.1-py3.6.egg/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-3.5.1-py3.6.egg/google/protobuf/internal/type_checkers.py", line 109, in CheckValue
    raise TypeError(message)
TypeError: 'Hola' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)

Can you help me?
Thanxs!

**Comment by qvs5010** [comment]
Hi Try to add -E s40, 

also, makesure when you registered you used -E s40, else you will bet baned.

python3 yowsup-cli demos --send 1234567 "Moo Moo" --config config.WhatsApp -E s40

**Comment by AragurDEV** [comment]
Closing due to inactivity.
