### ISSUE TITLE
error when trying run yowsup-cli

### ISSUE THREAD

**Issue by albaizzz** [AragurDEV/yowsup#69]
I got this error, and i'm trying to install imagemagick in my mac (OS Sierra) but still failed/error

` File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Wand-0.4.4-py3.6.egg/wand/api.py", line 180, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Wand-0.4.4-py3.6.egg/wand/api.py", line 135, in load_library
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 384, in <module>
    if not parser.process():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 288, in process
    self.startSendClient()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 330, in startSendClient
    from yowsup.demos import sendclient
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/__init__.py", line 2, in <module>
    from .layer_authentication import YowAuthenticationProtocolLayer
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/layer_authentication.py", line 4, in <module>
    from yowsup.common.tools import TimeTools
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/common/tools.py", line 13, in <module>
    from preview_generator.manager import PreviewManager
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/preview_generator-0.2.3-py3.6.egg/preview_generator/manager.py", line 8, in <module>
    from preview_generator.preview.builder.office__libreoffice import OfficePreviewBuilderLibreoffice  # nopep8
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/preview_generator-0.2.3-py3.6.egg/preview_generator/preview/builder/office__libreoffice.py", line 17, in <module>
    from preview_generator.preview.generic_preview import PreviewBuilder
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/preview_generator-0.2.3-py3.6.egg/preview_generator/preview/generic_preview.py", line 9, in <module>
    from preview_generator import file_converter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/preview_generator-0.2.3-py3.6.egg/preview_generator/file_converter.py", line 9, in <module>
    from wand.image import Image as WImage
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Wand-0.4.4-py3.6.egg/wand/image.py", line 20, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Wand-0.4.4-py3.6.egg/wand/api.py", line 206, in <module>
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick`

**Comment by AragurDEV** [comment]
Can you verify that you're using the right version?

**Comment by AragurDEV** [comment]
Please reopen the issue if the issue is still occurring with the latest version
