### ISSUE TITLE
image_send failed

### ISSUE THREAD

**Issue by hiral2cool** [AragurDEV/yowsup#80]
[connected]:/image send 91xxxxxxxx "D:\back.jpg"
[connected]:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): mmg.whatsapp.net
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer __init__() got an unexpected keyword argument 'strict'
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\yowsup2-2.5.7-py3.6.egg\yowsup\layers\protocol_media\mediauploader.py", line 153, in run
    response = requests.post(uploadUrl, data=data, headers=headers)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 292, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 238, in _get_conn
    return conn or self._new_conn()
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 562, in _new_conn
    strict=self.strict)
TypeError: __init__() got an unexpected keyword argument 'strict'

ERROR:yowsup.demos.cli.layer:Upload file D:\back.jpg to https://mmg.whatsapp.net/u/f/ACrRLTLTpVCzhHN0th8Fa1sU4FQABW3LTAMd4A/AjrNmGM3VnKM4Y-I2JEdCw2lCmWgShDapTrn3m85GSgN for 91xxxxxxxxxxxx@s.whatsapp.net failed!

**Comment by AragurDEV** [comment]
Hmm seems like an issue in urllib3.
Can you please tell me which version of urllib3 you are using?

**Comment by hiral2cool** [comment]
i am using urllib3 v1.23

**Comment by hiral2cool** [comment]
Ya working fine i there is problem with requests module urllib3 
we have to remove one parameter that i did and now its working 
thanks
