### ISSUE TITLE
I can't able to send the image &  document.

### ISSUE THREAD

**Issue by BodduSatya** [AragurDEV/yowsup#83]
>can any one help me to solve the following issue
```/image send xxxxxxxxx "/home/xxxxxx/xxx/uploads/ganesh.jpg"```

```python
image/jpeg
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer Value for header {content-length: 87340} must be of type str or bytes, not <class 'int'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 868, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tejith/sr/wadoc/yowsup/yowsup/layers/protocol_media/mediauploader.py", line 155, in run
    response = requests.post(uploadUrl, data=data, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {content-length: 87340} must be of type str or bytes, not <class 'int'>
ERROR:yowsup.demos.cli.layer:Upload file /home/xxx/xx/uploads/ganesh.jpg to https://mmg.whatsapp.net/u/f/X7DIaHKMbrs560-3c2CJZFsxpl0ABW-CWMnHyw/AueDuQFn6wbbbzZtMFUsMcCqbbShxyr0DwXCevkipqw- for xxxxxxxxxx@s.whatsapp.net failed!
RECEIVE: result
iq
```
Thanks in advance

**Comment by BodduSatya** [comment]
same exception for pdf also

application/pdf
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer Value for header {content-length: 73580} must be of type str or bytes, not <class 'int'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 868, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxx/xx/xxxx/yowsup/yowsup/layers/protocol_media/mediauploader.py", line 155, in run
    response = requests.post(uploadUrl, data=data, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {content-length: 73580} must be of type str or bytes, not <class 'int'>
ERROR:yowsup.demos.cli.layer:Upload file /home/XXXXXX/XXXXX/uploads/XXXXXXXX.pdf to https://mmg.whatsapp.net/u/f/iO-ZvzH-shw_-fWL5m2tCVsxqVMABW-ChfX4JA/AprXRPr7ZE3HP7UEErlkrfwWDBXmGvvAwVnX-Hg46B4g for XXXXXXXX@s.whatsapp.net failed!
RECEIVE: result
iq

**Comment by AragurDEV** [comment]
Please rename the issue and embed the log with the correspondending markdown syntax. 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by BodduSatya** [comment]
Hi AragurDEV,

`Issue title renamed and embed the log with the corresponding markdown syntax.`

**Comment by BodduSatya** [comment]
I am using following versions

>Python 3.6.5
>ubuntu18.04
>yowsup-cli  v2.0.15
>yowsup      v2.5.2

ImageMagick 7.0.8 ,ghostscript,pillow packages already installed.

yowsup from AragurDEV fork.

**Comment by BodduSatya** [comment]
@AragurDEV 
can you tell me the resolution for my issue.

**Comment by BodduSatya** [comment]
thank you AragurDEV, mike-weshop 
#30 issue already fixed.
working fine to me...
