### ISSUE TITLE
Video support missing

### ISSUE THREAD

**Issue by aero9** [AragurDEV/yowsup#84]
/video send xxxxxxxxxx  /root/yowsup/media/video.mp4

[connected]:INFO:urllib3.connectionpool:Starting new HTTPS connection (1): mmg.whatsapp.net
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer No module named 'av'
Traceback (most recent call last):
  File "/root/yowsup/yowsup/layers/protocol_media/mediauploader.py", line 168, in run
    self.successCallback(sourcePath, self.jid, result)
  File "/root/yowsup/yowsup/demos/cli/layer.py", line 587, in <lambda>
    successFn = lambda filePath, jid, url: self.doSendMedia(mediaType, filePath, url, jid, resultRequestUploadIqProtocolEntity.getIp(), caption)
  File "/root/yowsup/yowsup/demos/cli/layer.py", line 571, in doSendMedia
    entity = VideoDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to, caption = caption)
  File "/root/yowsup/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py", line 162, in fromFilePath
    preview = VideoTools.generatePreviewFromVideo(path)
  File "/root/yowsup/yowsup/common/tools.py", line 337, in generatePreviewFromVideo
    import av
ImportError: No module named 'av'
ERROR:yowsup.demos.cli.layer:Upload file /root/yowsup/media/video.mp4 

i try to install  av 
sudo pip3 install av

 Running setup.py install for av
    Could not find either libswresample or libavresample with pkg-config.
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/av/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wqhea6z6-record/install-record.txt --single-version-externally-managed --compile:
    running install

**also, how to view the encrypted video/audio files that i have received  ?** 

ubuntu 14.04

thanks

**Comment by AragurDEV** [comment]
Not included yet.
We will ad this in the future.

**Comment by aero9** [comment]
thanks
