### ISSUE TITLE
async syntaxError: invalid syntax

### ISSUE THREAD

**Issue by naushrambo** [AragurDEV/yowsup#87]
Getting

Traceback (most recent call last):
  File "yowsup-cli", line 384, in <module>
    if not parser.process():
  File "yowsup-cli", line 284, in process
    self.startCmdline()
  File "yowsup-cli", line 306, in startCmdline
    from yowsup.demos import cli
  File "/Applications/MAMP/htdocs/pythonpractice/wc/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/Applications/MAMP/htdocs/pythonpractice/wc/yowsup/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/Applications/MAMP/htdocs/pythonpractice/wc/yowsup/yowsup/demos/cli/layer.py", line 591
    successFn, self.onUploadError, self.onUploadProgress, async=False)
                                                              ^
SyntaxError: invalid syntax

when runnung 
python3 yowsup-cli demos --yowsup --login 143xxxxxx:passwsord

**Comment by AragurDEV** [comment]
Please add more informations.
OS you are using, Python version, etc..

**Comment by naushrambo** [comment]
Thanks For the reply, Problem solved after switching back to python 2.7, my previous python version was 3.7.0.
