### ISSUE TITLE
Erro when receive Live location 

### ISSUE THREAD

**Issue by iFernandoSousa** [AragurDEV/yowsup#94]
When I share a  **Live location** to a number in Yowsup, I got on error saying that  this feature  is not implemented it.

The message received is some like this (_Part of message was deleted to be a short one, to get  a real message just  share your real location with a number running in yowsup_)

```
<message type="media" id="6CAF441677B2FBDECE2E13617DC59098" from="5511999XXXXXX@s.whatsapp.net" t="1535852795" notify="Fernando Sousa">
<enc type="msg" v="2" mediatype="livelocation">
b'3\n!\x05&62R\xeb-\xbb\x9b\x83\xfeiJ\xfc\xe4S\xf3h\xa0p3\xd3\x94\xdep@\xa7\x0e\x9c\xd4w\x94n\x10\x03\x18\x00"\xe0\x13\xbf\xeaV\x86\xf8\x19q\x10\x9b)\x08\xb4YJ\x19N\xa1c\x95\xee\xfd\t\x9c\xc8\xe7/\xad 27\xa3X\xdb5*|P\xadl\xe7\x91\xd4Q\xf3\xde\x91\x14\xf6\xff\x14\x90\x7f\x91z\xe4\xfaBN\x085p\x13\x7f\x92\xc8"\xf5\x19\x81XRO\xe3\xd6b\x92a\x1f\x89\xfc\x01>\xa4\x1c\xbd\xd1#A@.jx(\xeb\xa7\xbb\x90\x94\xe2R\xea\xd4w\xd7mQ\x1by<\xb4\x9c\xb6\xa0\xb8nD\xce\xf1\xd7\x8d\xd6Z\x10Q&\xfa\xa1\xe8o\xb5\xeb\xd0\xf0\xa9\x9c\x02\x11 \x05\x8e\x0c\x1fq\x80\xf2\x1b5\x88\n\xbe\xbb\xf0\xf1xeawR2%\xa2\xc9\xdfV\x93\xb6lG\x8e\x1b\x1c(\x00\xca\xcc\x9b\xd4\xa95\x1d\x81\xfeD\xb9\xdaW\xa0\xfd\xf5\x9e|\xde6V\xcdw\xd8I@(\xd3y\xbd\xae\x08dLb\xc0\xcc\xdd`\xcc\xfd\xbd\xca=\xfc\xb9v\xd4BA\x9c\x8c\x9e\xc8\xc6uU\xf6,\x93\xc6\x9b\x1e\x7f\xc0y\xb6\xeb_mh\x10\xc3^\x1e|p\x0b\xdf\x12\xed5Q\x0cm\xa9{\xc5\xc9\xc7~\xe0\xdb\xc7\x14\x1b\xac\x16v\xae\x9c\x04\xd07\x1c\xfd6\x04s\x9b\xea8?\xd5S\x08m\x9alL\xc1@\x7f\x81\x12\x152<\x8d\xf8\xecp\xdfSj"\x8c\x1e\xd3\x8b=$\xf2\xf6\xb2\xf6sN\x1c\x1d\xb7\xa7\x89\xfc\xcf\xd2\roB\xaf\xad\xc8\xeb \xe3C\xf5\x91\xeb\xfc#\x82\rZ\n=\xc0\xdcz\x13\x15l\x05\x97\xcbt\x9a)n\xfe3_mJ1\xf8rKB\xa9\x97Y~d\x83@\x89\x04q\xfc:(\xb4\xb5\x7f\xe16\xa2Q\xe3\xd0\xa1T\xc0\xa3\xb4\x06\xfe,N\x91\x8b\xb3\xe5\xf3Bgm\xeaQT\xe4E\x1d;\xad\x01h"e^\xdb\x91\xd9hy\x98\xe3kQ8\xe0\x9d\x81\xc5\xdcR\x03Eu(/ 6yuwX\xd1\x0ch\xd8\xbdHv\x05\xe3\xcaR\xc3\x11+\x14O\r\xd2\x93\xf2\xeai\xdd\r;_\xe7\x1e\x93\xf7*M\xfa\xea\x9eLkM\xe7\xde\xe4k\xd828\'\xb1\xa4\xaf\x90%\xd4'
HEX:b'330a210526363252eb2dbb9b83fe694afce453f368a07033d394de7040a70e9cd477946e1003180022e013bfea5686f81971109b2908b4594a194ea16395eefd099cc8e72fad203237a358db352a7c50ad6ce791d451f3de9114f6ff14907f917ae4fa424e083570137f92c822f5198158524fe3d66292611f89fc013ea41cbdd12341402e6a7828eba7bb9094e252ead477d76d511b793cb49cb6a0b86e44cef1d78dd65a105126faa1e86fb5ebd0f0a99c021120058e0c1f7180f21b35880abebbf0f112fc99b312b36e1dac8d840491a3617e50318522b3bb7345747b23679d535128c685d8b0fb7b72c3fa1a9c801005ab0d4c99543b2de67019908b1b647cff53bd2a907b8a314b8d21357dbb620f41c991d130996f03c8e7037dafab1fbe824881487ab6bacab27e8a40dddae006bb36be41a0cf8ad53c1fb9f87b313d1ea9405532b8e0dbc7141bac1676ae9c04d0371cfd3604739bea383fd553086d9a6c4cc1407f811215323c8df8ec70df536a228c1ed38b3d24f2f6b2f6734e1c1db7a789fccfd20d6f42afadc8eb20e343f591ebfc23820d5a0a3dc0dc7a13156c0597cb749a296efe335f6d4a31f8724b42a997597e648340890471fc3a28b4b57fe136a251e3d0a154c0a3b406fe2c4e918bb3e5f342676dea5154e4451d3bad016822655edb91d9687998e36b5138e09d81c5dc52034575282f203679757758d10c68d8bd487605e3ca52c3112b144f0dd293f2ea69dd0d3b5fe71e93f72a4dfaea9e4c6b4de7dee46bd8323827b1a4af9025d4'
</enc>
</message>
```

**Comment by AragurDEV** [comment]
That's an intended behavoir because the live location feature isn't implemented yet on yowsup.

**Comment by iFernandoSousa** [comment]
Yeh, this is not implemented, but how can I do that?

Because if someone send me it or a many contact at the same time, that is not implemented too, this will stop my script and this will not return a receipt for WA so after receive many of this, my Yowsup stop to receive new messages because I do not send receipt for this messages.

I try to understand the wa_pb2.py and axolotl\layer_receive.py to try implement this
But it's a bit confusing :/

**Comment by AragurDEV** [comment]
Try to catch (```expect: ```) all errors in your script.
If there is an interal yowsup crash please reply back with logs.

**Comment by iFernandoSousa** [comment]
`We've already setup a session for this V3 message, letting bundled message fall through...
General Exception Unhandled
Traceback (most recent call last):
  File "/home/parallels/yowsupapi/common/stack.py", line 42, in start
    self.stack.loop()
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/stacks/yowstack.py", line 197, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 49, in receive
    self.onMessage(protocolTreeNode)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 90, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 103, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 151, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "/home/parallels/yowsupapi/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 258, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled`
